
name: tp1
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["rabbitmq-server"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 3s
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - CANT_AGENCIES=5
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
      mapper-1:
        condition: service_started
      mapper-2:
        condition: service_started
      queries-1-0:
        condition: service_started
      queries-1-1:
        condition: service_started
      reducer-1:
        condition: service_started
      queries-2-0:
        condition: service_started
      queries-2-1:
        condition: service_started
      reducer-2:
        condition: service_started
      queries-3-0:
        condition: service_started
      queries-3-1:
        condition: service_started
      reducer-3:
        condition: service_started
      queries-4-0:
        condition: service_started
      queries-4-1:
        condition: service_started
      reducer-4:
        condition: service_started
      # queries-5-0:
      #   condition: service_started
      # queries-5-1:
      #   condition: service_started
      # reducer-5:
      #   condition: service_started
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    volumes:
      - ./client.yml:/config.yml
      - ./results:/results
      - ../datasets/games_m.csv:/games.csv
      - ../datasets/reviews_m.csv:/reviews.csv
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  mapper-1:
    container_name: mapper-1
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./server.yml:/server.yml
  mapper-2:
    container_name: mapper-2
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./server.yml:/server.yml
  queries-1-0:
    container_name: queries-1-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=1
      - CLI_SHARD_ID=0
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-1-1:
    container_name: queries-1-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=1
      - CLI_SHARD_ID=1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-2-0:
    container_name: queries-2-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=2
      - CLI_SHARD_ID=0
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-2-1:
    container_name: queries-2-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=2
      - CLI_SHARD_ID=1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-3-0:
    container_name: queries-3-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=3
      - CLI_SHARD_ID=0
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-3-1:
    container_name: queries-3-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=3
      - CLI_SHARD_ID=1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-4-0:
    container_name: queries-4-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=0
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-4-1:
    container_name: queries-4-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  # queries-5-0:
  #   container_name: queries-5-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=0
  #   volumes:
  #     - ./server.yml:/server.yml
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-5-1:
  #   container_name: queries-5-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=1
  #   volumes:
  #     - ./server.yml:/server.yml
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  reducer-1:
    container_name: reducer-1
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  reducer-2:
    container_name: reducer-2
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=2
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  reducer-3:
    container_name: reducer-3
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=3
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  reducer-4:
    container_name: reducer-4
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=4
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
  # reducer-5:
  #   container_name: reducer-5
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=5
  #   volumes:
  #     - ./server.yml:/server.yml
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy