
name: tp1
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["rabbitmq-server"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 3s
    networks:
      - network
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - CANT_AGENCIES=5
    networks:
      network:
        ipv4_address: 10.5.1.1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
      mapper-1:
        condition: service_started
      mapper-2:
        condition: service_started
      # queries-1-0:
      #   condition: service_started
      # queries-1-1:
      #   condition: service_started
      # reducer-1:
      #   condition: service_started
      # queries-2-0:
      #   condition: service_started
      # queries-2-1:
      #   condition: service_started
      # reducer-2:
      #   condition: service_started
      # queries-3-0:
      #   condition: service_started
      # queries-3-1:
      #   condition: service_started
      # reducer-3:
      #   condition: service_started
      queries-4-0:
        condition: service_started
      queries-4-1:
        condition: service_started
      reducer-4:
        condition: service_started
      # reviver-1:
      #   condition: service_started
      # reviver-2:
      #   condition: service_started
      # reviver-3:
      #   condition: service_started
  mapper-1:
    container_name: mapper-1
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLI_MAPPER_ID=1
    networks:
      network:
        ipv4_address: 10.5.2.1
    volumes:
      - ./server.yml:/server.yml
      - ../database/mapper-1_database:/database
  mapper-2:
    container_name: mapper-2
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLI_MAPPER_ID=2
    networks:
      network:
        ipv4_address: 10.5.2.2
    volumes:
      - ./server.yml:/server.yml
      - ../database/mapper-2_database:/database
  # queries-1-0:
  #   container_name: queries-1-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=1
  #     - CLI_SHARD_ID=0
  #   networks:
  #     network:
  #       ipv4_address: 10.5.3.10
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-1-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-1-1:
  #   container_name: queries-1-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=1
  #     - CLI_SHARD_ID=1
  #   networks:
  #     network:
  #       ipv4_address: 10.5.3.11
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-1-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-1:
  #   container_name: reducer-1
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=1
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-1_database:/database
  #   networks:
  #     network:
  #       ipv4_address: 10.5.4.1
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-2-0:
  #   container_name: queries-2-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=0
  #   networks:
  #     network:
  #       ipv4_address: 10.5.3.20
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-2-1:
  #   container_name: queries-2-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=1
  #   networks:
  #     network:
  #       ipv4_address: 10.5.3.21
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-2:
  #   container_name: reducer-2
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=2
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-2_database:/database
  #   networks:
  #     network:
  #       ipv4_address: 10.5.4.2
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  queries-4-0:
    container_name: queries-4-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=0
    networks:
      network:
        ipv4_address: 10.5.3.30
    volumes:
      - ./server.yml:/server.yml
      - ../database/queries-4-0_database:/database
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-4-1:
    container_name: queries-4-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=1
    networks:
      network:
        ipv4_address: 10.5.3.31
    volumes:
      - ./server.yml:/server.yml
      - ../database/queries-4-1_database:/database
    depends_on:
      rabbitmq:
        condition: service_healthy
  reducer-4:
    container_name: reducer-4
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=4
    volumes:
      - ./server.yml:/server.yml
      - ../database/reducer-4_database:/database
    networks:
      network:
        ipv4_address: 10.5.4.3
    depends_on:
      rabbitmq:
        condition: service_healthy
 
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
  