
name: tp1
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["rabbitmq-server"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 3s
    networks:
      - network
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - CANT_AGENCIES=5
    networks:
      network:
        ipv4_address: 10.5.1.1
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
      mapper-1:
        condition: service_started
      mapper-2:
        condition: service_started
      queries-4-0:
        condition: service_started
      queries-4-1:
        condition: service_started
      reducer-4:
        condition: service_started
      reviver-1:
        condition: service_started
      reviver-2:
        condition: service_started
      reviver-3:
        condition: service_started
  mapper-1:
    container_name: mapper-1
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLI_MAPPER_ID=1
    networks:
      network:
        ipv4_address: 10.5.2.1
    volumes:
      - ./server.yml:/server.yml
      - ../database/mapper-1_database:/database
  mapper-2:
    container_name: mapper-2
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CLI_MAPPER_ID=2
    networks:
      network:
        ipv4_address: 10.5.2.2
    volumes:
      - ./server.yml:/server.yml
      - ../database/mapper-2_database:/database
  queries-4-0:
    container_name: queries-4-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=0
    networks:
      network:
        ipv4_address: 10.5.3.40
    volumes:
      - ./server.yml:/server.yml
      - ../database/queries-4-0_database:/database
    depends_on:
      rabbitmq:
        condition: service_healthy
  queries-4-1:
    container_name: queries-4-1
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=4
      - CLI_SHARD_ID=1
    networks:
      network:
        ipv4_address: 10.5.3.41
    volumes:
      - ./server.yml:/server.yml
      - ../database/queries-4-1_database:/database
    depends_on:
      rabbitmq:
        condition: service_healthy
  reducer-4:
    container_name: reducer-4
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=4
    volumes:
      - ./server.yml:/server.yml
      - ../database/reducer-4_database:/database
    networks:
      network:
        ipv4_address: 10.5.4.4
    depends_on:
      rabbitmq:
        condition: service_healthy
  reviver-1:
    container_name: reviver-1
    image: reviver:latest
    entrypoint: /reviver
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=1
    networks:
      network:
        ipv4_address: 10.5.6.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server.yml:/server.yml
      - ./name_ip.csv:/name_ip.csv
    depends_on:
      rabbitmq:
        condition: service_healthy
  reviver-2:
    container_name: reviver-2
    image: reviver:latest
    entrypoint: /reviver
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=2
    networks:
      network:
        ipv4_address: 10.5.6.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server.yml:/server.yml
      - ./name_ip.csv:/name_ip.csv
    depends_on:
      rabbitmq:
        condition: service_healthy
  reviver-3:
    container_name: reviver-3
    image: reviver:latest
    entrypoint: /reviver
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=3
    networks:
      network:
        ipv4_address: 10.5.6.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server.yml:/server.yml
      - ./name_ip.csv:/name_ip.csv
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
  