
name: tp1
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["rabbitmq-server"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 3s
    networks:
      - network
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - CANT_AGENCIES=5
    networks:
      - network
    volumes:
      - ./server.yml:/server.yml
    depends_on:
      rabbitmq:
        condition: service_healthy
      mapper-1:
        condition: service_started
      # mapper-2:
      #   condition: service_started
      queries-1-0:
        condition: service_started
      # queries-1-1:
      #   condition: service_started
      # queries-1-2:
      #   condition: service_started
      # queries-1-3:
      #   condition: service_started
      reducer-1:
        condition: service_started
      # queries-2-0:
      #   condition: service_started
      # queries-2-1:
      #   condition: service_started
      # queries-2-2:
      #   condition: service_started
      # queries-2-3:
      #   condition: service_started
      # reducer-2:
      #   condition: service_started
      # queries-3-0:
      #   condition: service_started
      # queries-3-1:
      #   condition: service_started
      # queries-3-2:
      #   condition: service_started
      # queries-3-3:
      #   condition: service_started
      # reducer-3:
      #   condition: service_started
      # queries-4-0:
      #   condition: service_started
      # queries-4-1:
      #   condition: service_started
      # queries-4-2:
      #   condition: service_started
      # queries-4-3:
      #   condition: service_started
      # reducer-4:
      #   condition: service_started
      # queries-5-0:
      #   condition: service_started
      # queries-5-1:
      #   condition: service_started
      # queries-5-2:
      #   condition: service_started
      # queries-5-3:
      #   condition: service_started
      # reducer-5:
      #   condition: service_started
  mapper-1:
    container_name: mapper-1
    image: mapper:latest
    entrypoint: /mapper
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - network
    volumes:
      - ./server.yml:/server.yml
      - ../database/mapper-1_database:/database
  # mapper-2:
  #   container_name: mapper-2
  #   image: mapper:latest
  #   entrypoint: /mapper
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/mapper-2_database:/database
  queries-1-0:
    container_name: queries-1-0
    image: query:latest
    entrypoint: /query
    environment:
      - CLI_QUERY_ID=1
      - CLI_SHARD_ID=0
    networks:
      - network
    volumes:
      - ./server.yml:/server.yml
      - ../database/queries-1-0_database:/database
    depends_on:
      rabbitmq:
        condition: service_healthy
  # queries-1-1:
  #   container_name: queries-1-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=1
  #     - CLI_SHARD_ID=1
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-1-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-1-2:
  #   container_name: queries-1-2
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=1
  #     - CLI_SHARD_ID=2
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-1-2_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-1-3:
  #   container_name: queries-1-3
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=1
  #     - CLI_SHARD_ID=3
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-1-3_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  reducer-1:
    container_name: reducer-1
    image: reducer:latest
    entrypoint: /reducer
    environment:
      - CLI_QUERY_ID=1
    volumes:
      - ./server.yml:/server.yml
      - ../database/reducer-1_database:/database
    networks:
      - network
    depends_on:
      rabbitmq:
        condition: service_healthy
  # queries-2-0:
  #   container_name: queries-2-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=0
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-2-1:
  #   container_name: queries-2-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=1
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-2-2:
  #   container_name: queries-2-2
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=2
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-2_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-2-3:
  #   container_name: queries-2-3
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=2
  #     - CLI_SHARD_ID=3
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-2-3_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-2:
  #   container_name: reducer-2
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=2
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-2_database:/database
  #   networks:
  #     - network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-3-0:
  #   container_name: queries-3-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=3
  #     - CLI_SHARD_ID=0
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-3-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-3-1:
  #   container_name: queries-3-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=3
  #     - CLI_SHARD_ID=1
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-3-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-3-2:
  #   container_name: queries-3-2
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=3
  #     - CLI_SHARD_ID=2
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-3-2_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-3-3:
  #   container_name: queries-3-3
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=3
  #     - CLI_SHARD_ID=3
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-3-3_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-3:
  #   container_name: reducer-3
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=3
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-3_database:/database
  #   networks:
  #     - network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-4-0:
  #   container_name: queries-4-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=4
  #     - CLI_SHARD_ID=0
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-4-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-4-1:
  #   container_name: queries-4-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=4
  #     - CLI_SHARD_ID=1
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-4-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-4-2:
  #   container_name: queries-4-2
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=4
  #     - CLI_SHARD_ID=2
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-4-2_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-4-3:
  #   container_name: queries-4-3
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=4
  #     - CLI_SHARD_ID=3
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-4-3_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-4:
  #   container_name: reducer-4
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=4
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-4_database:/database
  #   networks:
  #     - network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-5-0:
  #   container_name: queries-5-0
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=0
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-5-0_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-5-1:
  #   container_name: queries-5-1
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=1
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-5-1_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-5-2:
  #   container_name: queries-5-2
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=2
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-5-2_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # queries-5-3:
  #   container_name: queries-5-3
  #   image: query:latest
  #   entrypoint: /query
  #   environment:
  #     - CLI_QUERY_ID=5
  #     - CLI_SHARD_ID=3
  #   networks:
  #     - network
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/queries-5-3_database:/database
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  # reducer-5:
  #   container_name: reducer-5
  #   image: reducer:latest
  #   entrypoint: /reducer
  #   environment:
  #     - CLI_QUERY_ID=5
  #   volumes:
  #     - ./server.yml:/server.yml
  #     - ../database/reducer-5_database:/database
  #   networks:
  #     - network
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
networks:
  network:
    driver: bridge
  