
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - CANT_AGENCIES=5
    volumes:
      - ./server.yml:/config.yml
    depends_on:
      rabbitmq:
        condition: service_healthy

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    volumes:
      - ./client.yml:/config.yml
      - ./datasets/games.csv:/games.csv
      - ./datasets/reviews.csv:/reviews.csv
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # command: ["rabbitmq-server"]
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
    environment:
      RABBITMQ_DEFAULT_LOG_LEVEL: error
      RABBITMQ_LOG_LEVELS: "connection=error"
